[supervisord]
nodaemon=true
user=root

[program:web]
command=/start-web.sh
autostart=true
autorestart=true
stdout_logfile=NONE
stderr_logfile=NONE

[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3 --no-interaction
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker.log
user=www-data

[program:reverb]
command=php /var/www/html/artisan reverb:start
autostart=true
autorestart=true
user=www-data

; [program:maildev]
; command=npx maildev --web 1081 --smtp 2525
; autostart=true
; autorestart=true
; stdout_logfile=/var/www/html/storage/logs/maildev.log
; redirect_stderr=true
; user=root
